const BASE = 'https://www.carlogos.org/car-logos';

export const MAKE_LOGOS: Record<string, string> = {
  Audi:              `${BASE}/audi-logo.png`,
  Bmw:               `${BASE}/bmw-logo.png`,
  Chery:             `${BASE}/chery-logo.png`,
  Chevrolet:         `${BASE}/chevrolet-logo.png`,
  Citroen:           `${BASE}/citroen-logo.png`,
  Ford:              `${BASE}/ford-logo.png`,
  Gwm:               `${BASE}/great-wall-logo.png`,
  Haval:             `${BASE}/haval-logo.png`,
  Honda:             `${BASE}/honda-logo.png`,
  Hyundai:           `${BASE}/hyundai-logo.png`,
  Isuzu:             `${BASE}/isuzu-logo.png`,
  Kia:               `${BASE}/kia-logo.png`,
  'Land Rover':      `${BASE}/land-rover-logo.png`,
  Mahindra:          `${BASE}/mahindra-logo.png`,
  Mazda:             `${BASE}/mazda-logo.png`,
  'Mercedes-benz':   `${BASE}/mercedes-benz-logo.png`,
  'Mercedes-Benz':   `${BASE}/mercedes-benz-logo.png`,
  Mini:              `${BASE}/mini-logo.png`,
  Mitsubishi:        `${BASE}/mitsubishi-logo.png`,
  Nissan:            `${BASE}/nissan-logo.png`,
  Opel:              `${BASE}/opel-logo.png`,
  Proton:            `${BASE}/proton-logo.png`,
  Renault:           `${BASE}/renault-logo.png`,
  Toyota:            `${BASE}/toyota-logo.png`,
  Volkswagen:        `${BASE}/volkswagen-logo.png`,
  Volvo:             `${BASE}/volvo-logo.png`,
  Suzuki:            `${BASE}/suzuki-logo.png`,
  Jeep:              `${BASE}/jeep-logo.png`,
  Peugeot:           `${BASE}/peugeot-logo.png`,
  Subaru:            `${BASE}/subaru-logo.png`,
  Lexus:             `${BASE}/lexus-logo.png`,
  Jaguar:            `${BASE}/jaguar-logo.png`,
  Porsche:           `${BASE}/porsche-logo.png`,
  Dodge:             `${BASE}/dodge-logo.png`,
  Fiat:              `${BASE}/fiat-logo.png`,
  Alfa:              `${BASE}/alfa-romeo-logo.png`,
  'Alfa Romeo':      `${BASE}/alfa-romeo-logo.png`,
  Chrysler:          `${BASE}/chrysler-logo.png`,
  Jetour:            `${BASE}/jetour-logo.png`,
  Baic:              `${BASE}/baic-logo.png`,
  Datsun:            `${BASE}/datsun-logo.png`,
  Ram:               `${BASE}/ram-logo.png`,
};
